[project]
name = "query-near-text-tool"
version = "0.1.0"
description = "Tool to query from weaviate db"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "weaviate-client>=4.10.4",
    "pydantic",
] 