[project]
name = "list-pull-request-reviews"
version = "0.1.0"
description = "List GitHub pull request reviews"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "pydantic", "pygithub>=2.5.0",]
