[project]
name = "create-issue-comment"
version = "0.1.0"
description = "Create a GitHub issue comment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "pydantic", "pygithub==2.5.0",]
