[project]
name = "read-all-objects-tool"
version = "0.1.0"
description = "Tool to read all objects from a Weaviate collection"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "weaviate-client>=4.10.4",
    "pydantic",
] 