[project]
name = "create-outbound-call"
version = "0.1.0"
description = "Create an outbound call using HappyRobot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pydantic", "requests>=2.32.3"]
