name: Run Pytest on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13" ]

    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          cd libs/hyperpocket
          poetry install

      - name: Install Playwright Browsers
        run: |
          cd libs/hyperpocket
          poetry run playwright install

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Lint code with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github
        continue-on-error: true

      - name: Check code formatting with Ruff
        run: ruff format --diff
        continue-on-error: true

      - name: Test with pytest
        env:
          POCKET_ENV: TEST
        run: |
          echo "POCKET ENV : $POCKET_ENV"
          
          cd libs/hyperpocket
          poetry add pytest
          poetry add pytest-cov
          
          poetry run pytest  -v --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html