name: Run Pytest on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "pypy3.10", "3.10", "3.11", "3.12", "3.13" ]

    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        working-directory: libs/hyperpocket
        run: |
          uv sync --dev

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker service
        run: |
          sudo service docker start
          sudo service docker status

      - name: Pull Docker Image (Manually)
        run: docker pull python:3.11-slim

      - name: Lint code with Ruff
        run: |
          uv run ruff check --output-format=github
        continue-on-error: true

      - name: Check code formatting with Ruff
        run: uv run ruff format --diff
        continue-on-error: true

      - name: Test with pytest
        working-directory: libs/hyperpocket
        run: |
          uv run pytest  -v --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html